/**
 * Lifeframe Sync & Media API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Normalized coordinates (0.0 - 1.0) compatible with YOLO, ONNX, and digiKam tagRegion
 */
export interface BoundingBox { 
    /**
     * Top-left X coordinate normalized (0.0 to 1.0)
     */
    x: number;
    /**
     * Top-left Y coordinate normalized (0.0 to 1.0)
     */
    y: number;
    /**
     * Bounding box width normalized (0.0 to 1.0)
     */
    width: number;
    /**
     * Bounding box height normalized (0.0 to 1.0)
     */
    height: number;
}

