/**
 * Lifeframe Sync & Media API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DeviceStatus { 
    device_id: string;
    device_name: string;
    device_type: DeviceStatusDeviceTypeEnum;
    battery_percentage?: number | null;
    is_charging?: boolean | null;
    storage_free_bytes?: number | null;
    storage_total_bytes?: number | null;
    client_version: string;
    last_sync_at?: string | null;
    /**
     * Current sync state (e.g. idle, syncing, paused, error)
     */
    sync_status?: string | null;
}
export enum DeviceStatusDeviceTypeEnum {
    Desktop = 'desktop',
    MobileAndroid = 'mobile_android',
    MobileIos = 'mobile_ios',
    Unknown = 'unknown'
};



