/**
 * Lifeframe Sync & Media API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Parsed photographic technical metadata
 */
export interface ExifData { 
    make?: string | null;
    model?: string | null;
    lens?: string | null;
    focal_length?: number | null;
    f_number?: number | null;
    iso?: number | null;
    /**
     * Formatted shutter speed e.g. 1/250s
     */
    exposure_time?: string | null;
}

