/**
 * Lifeframe Sync & Media API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BoundingBox } from './bounding-box';


/**
 * Detected or tagged face region ready for ONNX/YOLO and digiKam compatibility
 */
export interface FaceTag { 
    /**
     * Unique face detection ID
     */
    id: string;
    /**
     * ID of identified person if assigned
     */
    person_id?: string | null;
    /**
     * Recognized or labeled person name
     */
    person_name?: string | null;
    /**
     * Detection confidence score (0.0 to 1.0)
     */
    confidence?: number | null;
    /**
     * Whether verified by user or auto-detected by AI
     */
    is_confirmed?: boolean;
    box: BoundingBox;
}

