/**
 * Lifeframe Sync & Media API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * GPS coordinate information
 */
export interface GeoLocation { 
    latitude: number;
    longitude: number;
    altitude?: number | null;
}

