/**
 * Lifeframe Sync & Media API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Identified person entity for facial clustering
 */
export interface Person { 
    /**
     * Unique person identifier
     */
    id: string;
    /**
     * Person full name or label
     */
    name: string;
    /**
     * Face tag ID used as avatar
     */
    thumbnail_face_id?: string | null;
    /**
     * Number of photos tagged with this person
     */
    photo_count?: number;
}

