/**
 * Lifeframe Sync & Media API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FaceTag } from './face-tag';
import { GeoLocation } from './geo-location';
import { ExifData } from './exif-data';


export interface Photo { 
    /**
     * Unique UUID or identifier
     */
    id: string;
    /**
     * Original filename e.g. IMG_2026.JPG
     */
    filename: string;
    /**
     * Relative file path from root storage
     */
    relative_path: string;
    /**
     * File size in bytes
     */
    size_bytes: number;
    /**
     * SHA-256 hash checksum for integrity & deduplication
     */
    hash_sha256: string;
    /**
     * MIME type e.g. image/jpeg, image/png, image/heic
     */
    mime_type: string;
    /**
     * Image width in pixels
     */
    width?: number | null;
    /**
     * Image height in pixels
     */
    height?: number | null;
    /**
     * Star rating (0-5, matching digiKam rating)
     */
    rating?: number;
    /**
     * Date captured from EXIF
     */
    date_taken?: string | null;
    /**
     * File modification timestamp
     */
    date_modified: string;
    /**
     * Parent album ID if assigned
     */
    album_id?: string | null;
    /**
     * Keywords and general tags
     */
    tags?: Array<string>;
    /**
     * Detected faces and regions
     */
    faces?: Array<FaceTag>;
    gps?: GeoLocation;
    exif?: ExifData;
    /**
     * Library root path where the photo resides
     */
    library_path?: string | null;
}

