/**
 * Lifeframe Sync & Media API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Album } from './album';
import { Photo } from './photo';
import { Person } from './person';


export interface SyncManifest { 
    server_id: string;
    server_name: string;
    generated_at: string;
    total_photos: number;
    total_size_bytes: number;
    photos: Array<Photo>;
    albums: Array<Album>;
    people?: Array<Person>;
}

