/**
 * Lifeframe Sync & Media API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UploadResponse { 
    success: boolean;
    photo_id: string;
    relative_path: string;
    message: string;
}

